
name: front server
on:
  #pull_request:
  push:
    branches: [main]
    #types: [closed]
    # paths:
    #  - "live/**"


jobs:
  integrate:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: echo "${{secrets.KEY_PRIVATE}}" > server-key.pem
      - run: chmod 400 server-key.pem
      - run: ssh -i "server-key.pem" ubuntu@ec2-52-14-122-20.us-east-2.compute.amazonaws.com
      - run: ls
      # - run: docker login -u ${{secrets.USERNAME_CANISTER}} -p ${{secrets.PASSWORD_CANISTER}} cloud.canister.io:5000
      # - run: cd live && npm install && npm run package && docker build -t "cloud.canister.io:5000/msmarcks/sol:latest" .
      # - run: docker push cloud.canister.io:5000/msmarcks/sol:latest
