
name: FRONTEND server
on:
  pull_request:
    branches: [main]
    types: [closed]
    paths:
      - "Frontend/**"


jobs:
  integrate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: docker login -u ${{secrets.USERNAME_CANISTER}} -p ${{secrets.PASSWORD_CANISTER}} cloud.canister.io:5000
      - run: cd Frontend && npm install && npm run build && docker build -t "cloud.canister.io:5000/nv47/frontend:latest" .
      - run: docker push cloud.canister.io:5000/nv47/frontend:latest
      - name: andrewtwydell/ssh
        uses: AndrewTwydell/ssh-workflow@1.0.0
        with:
          # SSH Host
          host: ${{secrets.SSH_HOST}}
          # User name
          user: ${{secrets.SSH_USER}}
          # User Password
          password: ${{secrets.SSH_PASS}}
          # Script to Run
          script: |
            docker login -u ${{secrets.USERNAME_CANISTER}} -p ${{secrets.PASSWORD_CANISTER}} cloud.canister.io:5000
            docker ps -a -q --filter "name=frontapp" | grep -q . && docker stop frontapp && docker rm -fv frontapp && docker image rm cloud.canister.io:5000/nv47/frontend:latest || echo ""
            docker run --name frontapp -p "4001:80" -d cloud.canister.io:5000/nv47/frontend:latest
            exit
